import test from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import WebSocket from 'ws';
import { createApp } from '../src/server/index.js';
function waitFor(socket,type){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error(`等待 ${type} 超时`)),1500);const listener=raw=>{const message=JSON.parse(raw);if(message.type!==type)return;clearTimeout(timer);socket.off('message',listener);resolve(message);};socket.on('message',listener);});}
async function setup(t){const app=createApp();app.server.listen(0,'127.0.0.1');await once(app.server,'listening');t.after(async()=>{app.realtime.stop();for(const client of app.wss.clients)client.terminate();await new Promise(resolve=>app.server.close(resolve));});return {app,port:app.server.address().port};}
async function ws(port){const socket=new WebSocket(`ws://127.0.0.1:${port}/ws`);await once(socket,'open');return socket;}
test('HTTP 页面与 WebSocket 完整对局链路可用',async t=>{const {port}=await setup(t);const response=await fetch(`http://127.0.0.1:${port}/`);assert.equal(response.status,200);assert.match(await response.text(),/在线五子棋/);const first=await ws(port),createdP=waitFor(first,'state');first.send(JSON.stringify({type:'create',gameId:'gomoku'}));const created=await createdP;assert.match(created.room.id,/^[A-Z2-9]{6}$/);const second=await ws(port),joinedP=waitFor(second,'state');second.send(JSON.stringify({type:'join',roomId:created.room.id}));const joined=await joinedP;assert.equal(joined.room.viewer.index,2);const movedP=waitFor(first,'state');first.send(JSON.stringify({type:'action',action:{type:'place',row:7,col:7}}));const moved=await movedP;assert.equal(moved.room.state.board[7][7],1);assert.equal(moved.room.version,1);});
test('WebSocket 斗地主三人到齐后自动发牌且快照隔离手牌',async t=>{const {port}=await setup(t),s=[await ws(port),await ws(port),await ws(port)];let p=waitFor(s[0],'state');s[0].send(JSON.stringify({type:'create',gameId:'doudizhu'}));const created=await p;p=waitFor(s[1],'state');s[1].send(JSON.stringify({type:'join',roomId:created.room.id}));await p;const dealt=s.map(x=>waitFor(x,'state'));s[2].send(JSON.stringify({type:'join',roomId:created.room.id}));const states=await Promise.all(dealt);assert.equal(states[0].room.state.phase,'bidding');assert.deepEqual(states[0].room.state.handCounts,[17,17,17]);assert.notDeepEqual(states[0].room.state.hand,states[1].room.state.hand);assert.equal('hands'in states[0].room.state,false);});
test('WebSocket 麻将四人到齐自动开局并为每个连接隐藏他家手牌',async t=>{const {port}=await setup(t),s=[];for(let i=0;i<4;i++)s.push(await ws(port));let p=waitFor(s[0],'state');s[0].send(JSON.stringify({type:'create',gameId:'mahjong'}));const created=await p;for(let i=1;i<3;i++){p=waitFor(s[i],'state');s[i].send(JSON.stringify({type:'join',roomId:created.room.id}));await p;}const dealt=s.map(x=>waitFor(x,'state'));s[3].send(JSON.stringify({type:'join',roomId:created.room.id}));const states=await Promise.all(dealt);assert.equal(states[0].room.state.phase,'playing');assert.deepEqual(states[0].room.state.handCounts,[14,13,13,13]);assert.deepEqual(states.map(x=>x.room.state.hand.length),[14,13,13,13]);assert.equal('hands'in states[0].room.state,false);});
